name: Lint/Test/Build
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "checkou code"
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: echo "install dependencies"
        run: npm ci
      - name: Run Lint
        run: echo "execute lint"
        run: lint
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: npm build